### ISSUE TITLE
Off by One Error in Topview Numbers

### ISSUE THREAD

**Issue by DNAcer** [404Wolf/NATuG3#2]
<img width="788" alt="TopviewNumbersOff" src="https://user-images.githubusercontent.com/118033291/201461483-e77f80ce-8a85-42cd-915d-20c30c546bab.png">

As you can easily see in this image, in the Domains tab, domain 2 has the small angle, but in the topview image, domain 3 has the small angle. That seems to be a general state - all angles appear one over in top view.

**Comment by 404Wolf** [comment]
Issue: index 0 +1 solution makes them all 1 off. Fix: Rotate labels by 1.

**Comment by 404Wolf** [comment]
Issue has been fixed
